declare namespace _default {
    export { base };
    export { tendermint };
    export { auth };
    export { bank };
    export { crisis };
    export { distribution };
    export { evidence };
    export { gov };
    export { mint };
    export { params };
    export { slashing };
    export { staking };
    export { upgrade };
    export { tx };
    export { ibc };
}
export default _default;
import * as base from "./base";
import * as tendermint from "./tendermint";
import * as auth from "./auth";
import * as bank from "./bank";
import * as crisis from "./crisis";
import * as distribution from "./distribution";
import * as evidence from "./evidence";
import * as gov from "./gov";
import * as mint from "./mint";
import * as params from "./params";
import * as slashing from "./slashing";
import * as staking from "./staking";
import * as upgrade from "./upgrade";
import * as tx from "./tx";
import * as ibc from "./ibc";
